fix ci-config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,7 +43,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        node: [16, 18, 20, 22]
+        node: [18, 20, 22]
         chai: [4, 5]
 
     steps:
@@ -56,6 +56,7 @@ jobs:
         with:
           node-version: ${{ matrix.node }}
           cache: pnpm
+        run: node -v
       - name: Install Dependencies
         run: |
           pnpm install --frozen-lockfile
@@ -64,3 +65,30 @@ jobs:
         run: pnpm lint
       - name: Run Tests
         run: pnpm test
+
+  validate-success:
+    needs: ["tries"]
+    runs-on: ubuntu-latest
+    outputs:
+      success: ${{ steps.set-output.outputs.success }}
+    steps:
+      - id: set-output
+        run: echo "success=true" >> $GITHUB_OUTPUT
+
+  notify-success:
+    name: CI pipeline succeeded
+    needs: ["validate-success"]
+    if: always() # Always run, so we never skip this required check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Note Pipeline Passed
+        run: |
+          msgPrefix="Pipeline #${{ github.run_id }} finished"
+          passed="${{ needs.validate-success.outputs.success }}"
+          if [[ "$passed" == "true" ]]; then
+            echo "${msgPrefix}, PR passed all tests."
+            exit 0
+          else
+            echo "${msgPrefix}, but with failures. Check left sidebar summary to see which jobs failed."
+            exit 1
+          fi
